spring.application.name=worker
server.port=8181
spring.webflux.base-path=/worker
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example=DEBUG
# MongoDB
#spring.data.mongodb.uri=mongodb://localhost:27018/orderdb - Sin docker
spring.data.mongodb.uri=mongodb://mongo:27017/orderdb
# Kafka
#spring.kafka.bootstrap-servers=localhost:9092 - Sin docker
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=com.global.worker.domain.model.OrderMessage
# Redis
#spring.data.redis.host=localhost - Sin docker
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2000
# API Go
#go.api.base-url=http://localhost:8080 # Sin docker
go.api.base-url=http://api-go:8080